secret_key: como>>milano
api_tokens:
 cuu_BXgl2Zjii4_EU2NpZ8c7sYATQnDefc7issckc7LwGxpR15hh-g: silvio
 Cz8ABnYogyCu5KBjs7JfhxAR_WCEPYvdG0UxtLW4AoHoy3yGY5AGRQ: andrea
allowed_ip:
- 128.116.133.48
- 151.30.142.168
- 127.0.0.1