collections_lang:
- it
- en
- fr
- de
- nl
- es
mongourl: mongodb://localhost:27017
post_process:
  last_processed_id: Mw2sTeo_upO1iGqDw4xaFkOXHFuX4aid7hPL1WmZNnZA2dtLZpQ3jEIBGkU7BvdR5CCKzqSZNHx0tSrdrv2PlA
  last_processed_id_de: null
  last_processed_id_en: null
  last_processed_id_es: null
  last_processed_id_fr: null
  last_processed_id_nl: null
  last_processed_id_tr: null
scraper:
  newsriver_api:
  - sBBqsGXiYgF0Db5OV5tAw-YX7LO2k1G_-c4hiC3impbrVk28bIQ7TKT1p6Egz9vrn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAwyDwTBcmusmyclF2DJQMGXzq3w96QlMqw3KrGN772WETn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAwyDwTBcmusmyclF2DJQMGXwdTtlqoiFjohlircTRbjTVn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw0qEsNkUdZjT9lAgq0YtkxoDyiGAcVcfuEZOaoHNRgd_n2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw0qEsNkUdZjT9lAgq0YtkxqeWhxI2MWq4hxoWw_PQDAMn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw0qEsNkUdZjT9lAgq0Ytkxrcf3h1pG1qGQmmLqj3ICRtn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw-Jb2dMH9MSyvbTy8S7glfSZsD2Xztv-s9OeE6OPqJ_-n2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw98Pu7pQ6o1uDGmdvkhOLWcZMnN4bs4Df4RXM5MdO6IBn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw98Pu7pQ6o1uDGmdvkhOLWfIS2D_Ok7qp48XzMx5qypdn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw98Pu7pQ6o1uDGmdvkhOLWf-l55FqqgcRrCcXbAnc1HXn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw98Pu7pQ6o1uDGmdvkhOLWfn0E7tV7Zs1-2z9LIlrWCcn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw98Pu7pQ6o1uDGmdvkhOLWfBmZfbnQnIZ9Db2oOHRsrhn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw98Pu7pQ6o1uDGmdvkhOLWcfALlNit8EUXV4sOhH98HWn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw98Pu7pQ6o1uDGmdvkhOLWdHjzDzgS2IrSmtJ3KkmwL9n2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw98Pu7pQ6o1uDGmdvkhOLWceAsFvO7LyF6xSfplknrvBn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw98Pu7pQ6o1uDGmdvkhOLWfrUkmpnY6LF4rMVqaCsc_Qn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAw98Pu7pQ6o1uDGmdvkhOLWeJGV4qpYsh0osjAFNB44fLn2pHZrSf1gT2PUujH1YaQA
  - sBBqsGXiYgF0Db5OV5tAwzFUXbd7H1JfChjkkDxLkfwVd-3ad7hq73CTVTIadygin2pHZrSf1gT2PUujH1YaQA
  sort_by:
    discover_date: discoverDate
    read_time: metadata.readTime.seconds
    score: _score
  sort_order:
    asc: ASC
    desc: DESC
  start_date: 2020-05-13 09:01:56.349000
  start_date_de: 2020-05-13 13:15:41.016000
  start_date_en: 2020-05-12 16:08:49.572000
  start_date_es: 2020-05-12 18:17:57.220000
  start_date_fr: 2020-05-13 10:20:53.229000
  start_date_nl: 2020-05-13 06:35:40.562000
  start_date_tr: 2019-12-01 00:00:00
